### ISSUE TITLE
Webdata instead of Maybe

### ISSUE THREAD

**Issue by note89** [jahewson/elm-graphql#11]
Would it be a good idea to use a more granular approach to fetching than just `Maybe` ? 
[http://blog.jenkster.com/2016/06/how-elm-slays-a-ui-antipattern.html](url)

In the long term when Grahql supports something like `defer` that would be real useful i think.

**Comment by jahewson** [comment]
The use of Maybe in elm-graphql is to represent nullable types, i.e. all non-list types in GraphQL which don't end with `!`, so a `String!` becomes `String`, and a `String` becomes `Maybe String`. There's no more granularity than that.

GraphQL support for `defer`(https://github.com/facebook/relay/issues/288) is an interesting future prospect, but given that it's at the fragment level rather than the type level, I see it being another, higher, level of indirection, so you might see a type such as `Deferred Maybe String`, which would be a deferred nullable string.
