### ISSUE TITLE
change endpointUrl  default?

### ISSUE THREAD

**Issue by note89** [jahewson/elm-graphql#13]
The endpoint **url** now defaults to whatever is set in `graphql-make.sh`
I think it would be better that it defaults to `/graphql` so this does not have to be changed for production use.

**Comment by jahewson** [comment]
One of my goals is that the generated index.html can be run directly from a file:// URL without having to set up a server, so that getting up and running is really easy, so we have to keep localhost as the default. We also need to specify the full URL for the build process.

To handle your case I've added a third, optional build parameter in `graphql-make`, which sets the URL in the generated code separately from the URL used for schema introspection during the build, use it as follows:

```shell
$make src/GraphQL/StarWars.graphql "http://localhost:8080/graphql" "/graphql"
```

This landed in 712bdbf1705a9e9732353c06081896e839e9bbfc.
